spring.application.name=WebQuanLyCafe
server.port=8081
# MySQL — chạy script SQL tạo DB WebCafe trước, rồi chỉnh user/password
spring.datasource.url=jdbc:mysql://localhost:3306/WebCafe?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.timeout=30m
